// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIJnIJAIPXrvdgF2gsVUBIUbZIafuURk',
    appId: '1:883450804613:web:c0bbdf7e7fc1ca9408ecec',
    messagingSenderId: '883450804613',
    projectId: 'musicappflutter-52bd8',
    authDomain: 'musicappflutter-52bd8.firebaseapp.com',
    storageBucket: 'musicappflutter-52bd8.firebasestorage.app',
    measurementId: 'G-T7WZZ36J4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTm8AD-Vu5LChw-wDi0xv-MQlGGrZndOg',
    appId: '1:883450804613:android:0b28a651902b913008ecec',
    messagingSenderId: '883450804613',
    projectId: 'musicappflutter-52bd8',
    storageBucket: 'musicappflutter-52bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ySCr3kgIAxMm3x6MZU2JhLL4gSDimCQ',
    appId: '1:883450804613:ios:1d154522d9e7f60a08ecec',
    messagingSenderId: '883450804613',
    projectId: 'musicappflutter-52bd8',
    storageBucket: 'musicappflutter-52bd8.firebasestorage.app',
    iosBundleId: 'project.musicapp.musicAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ySCr3kgIAxMm3x6MZU2JhLL4gSDimCQ',
    appId: '1:883450804613:ios:1d154522d9e7f60a08ecec',
    messagingSenderId: '883450804613',
    projectId: 'musicappflutter-52bd8',
    storageBucket: 'musicappflutter-52bd8.firebasestorage.app',
    iosBundleId: 'project.musicapp.musicAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABIJnIJAIPXrvdgF2gsVUBIUbZIafuURk',
    appId: '1:883450804613:web:352a52f8fdcf28ed08ecec',
    messagingSenderId: '883450804613',
    projectId: 'musicappflutter-52bd8',
    authDomain: 'musicappflutter-52bd8.firebaseapp.com',
    storageBucket: 'musicappflutter-52bd8.firebasestorage.app',
    measurementId: 'G-2P46NDD7FM',
  );
}
